"""Airflow Agent for generating DAGs, TaskGroups, sensors, and dynamic tasks."""
from typing import Dict, List, Optional
from config.logging_config import get_logger
from services.llm_service import get_llm_service
from services.rag_service import get_rag_service

logger = get_logger("airflow_agent")

class AirflowAgent:
    """Specialized agent for Apache Airflow DAG design."""

    SYSTEM_PROMPT = """You are an expert Apache Airflow Data Engineer. You specialize in:
- Designing clean, idempotent Airflow DAGs
- Using TaskGroups to organize complex tasks
- Implementing Sensors (FileSensor, SqlSensor, ExternalTaskSensor) for dependencies
- Generating dynamic tasks and task generation from metadata
- Managing connections, variables, and XComs
- Tuning scheduler performance and retry logic

Always provide production-ready Python Airflow DAG code with comments."""

    def __init__(self):
        self.llm_service = get_llm_service()
        self.rag_service = get_rag_service()

    def process(self, query: str, context: str = "") -> str:
        """Process an Airflow-related query."""
        rag_context = self.rag_service.get_context(query, k=3)
        full_prompt = f"""{self.SYSTEM_PROMPT}

Context from knowledge base:
{rag_context}

User Query: {query}

Additional Context: {context}

Provide a comprehensive response with Airflow DAG Python examples where applicable."""

        return self.llm_service.generate(
            full_prompt,
            system_prompt=self.SYSTEM_PROMPT,
            temperature=0.3
        )

    def generate_dag(self, dag_id: str, schedule_interval: str = "@daily", tasks: List[str] = None) -> str:
        """Generate a basic Airflow DAG."""
        tasks = tasks or ["extract", "transform", "load"]
        tasks_creation = []
        tasks_flow = " >> ".join(tasks)

        for task in tasks:
            tasks_creation.append(f"""    {task}_task = EmptyOperator(
        task_id='{task}',
    )""")

        tasks_code = "\n\n".join(tasks_creation)

        dag_code = f"""from datetime import datetime, timedelta
from airflow import DAG
from airflow.operators.empty import EmptyOperator

default_args = {{
    'owner': 'data_engineering',
    'depends_on_past': False,
    'start_date': datetime(2026, 1, 1),
    'email_on_failure': False,
    'email_on_retry': False,
    'retries': 2,
    'retry_delay': timedelta(minutes=5),
}}

with DAG(
    '{dag_id}',
    default_args=default_args,
    description='Automated DAG generated by Data Engineering Copilot',
    schedule_interval='{schedule_interval}',
    catchup=False,
    tags=['production', 'data_engineering'],
) as dag:

{tasks_code}

    {tasks_flow}
"""
        return dag_code

    def generate_dag_with_sensor(self, dag_id: str, sensor_task_id: str = "wait_for_file") -> str:
        """Generate a DAG that begins with a FileSensor inside a TaskGroup."""
        dag_code = f"""from datetime import datetime, timedelta
from airflow import DAG
from airflow.sensors.filesystem import FileSensor
from airflow.utils.task_group import TaskGroup
from airflow.operators.python import PythonOperator

default_args = {{
    'owner': 'data_engineering',
    'start_date': datetime(2026, 1, 1),
    'retries': 1,
    'retry_delay': timedelta(minutes=1),
}}

def process_file_callback():
    print("Processing file detected by sensor...")

with DAG(
    '{dag_id}',
    default_args=default_args,
    schedule_interval=None,
    catchup=False,
) as dag:

    with TaskGroup('ingestion_group', tooltip="Ingestion Stage") as ingestion_group:
        file_sensor = FileSensor(
            task_id='{sensor_task_id}',
            filepath='/data/incoming/source_data.csv',
            fs_conn_id='fs_default',
            poke_interval=30,
            timeout=600,
        )

        process_task = PythonOperator(
            task_id='process_sensor_data',
            python_callable=process_file_callback,
        )

        file_sensor >> process_task
"""
        return dag_code


def get_airflow_agent() -> AirflowAgent:
    """Get Airflow agent instance."""
    return AirflowAgent()
