"""dbt Agent for generating models, tests, snapshots, and macros."""
from typing import Dict, List, Optional
from config.logging_config import get_logger
from services.llm_service import get_llm_service
from services.rag_service import get_rag_service

logger = get_logger("dbt_agent")

class DbtAgent:
    """Specialized agent for dbt (data build tool) tasks."""

    SYSTEM_PROMPT = """You are an expert dbt (data build tool) Analytics Engineer. You specialize in:
- Writing dbt models (SQL, Python) using best practice design (staging, intermediate, marts)
- Defining source and model tests in schema.yml
- Creating snapshots for SCD Type 2 history tracking
- Writing Jinja macros for reusable query logic
- Designing dbt projects, configuration, and documentation
- Setting up semantic layers and metrics

Always provide production-ready dbt SQL code and schema YAML configs."""

    def __init__(self):
        self.llm_service = get_llm_service()
        self.rag_service = get_rag_service()

    def process(self, query: str, context: str = "") -> str:
        """Process a dbt-related query."""
        rag_context = self.rag_service.get_context(query, k=3)
        full_prompt = f"""{self.SYSTEM_PROMPT}

Context from knowledge base:
{rag_context}

User Query: {query}

Additional Context: {context}

Provide a comprehensive response with dbt code and schema definitions where applicable."""

        return self.llm_service.generate(
            full_prompt,
            system_prompt=self.SYSTEM_PROMPT,
            temperature=0.3
        )

    def generate_model(self, model_name: str, source_table: str, columns: List[str]) -> str:
        """Generate a dbt model SQL."""
        cols_str = ",\n    ".join(columns)
        model_sql = f"""with source as (
    select * from {{{{ source('raw', '{source_table}') }}}}
),

renamed as (
    select
        {cols_str}
    from source
)

select * from renamed
"""
        return model_sql

    def generate_schema_yml(self, model_name: str, columns: List[Dict]) -> str:
        """Generate a schema.yml configuration with tests."""
        yaml_lines = [
            "version: 2",
            "",
            "models:",
            f"  - name: {model_name}",
            "    description: \"Model generated by Data Engineering Copilot.\"",
            "    columns:"
        ]

        for col in columns:
            col_name = col.get("name", "")
            yaml_lines.append(f"      - name: {col_name}")
            yaml_lines.append(f"        description: \"The {col_name} field.\"")
            tests = []
            if not col.get("nullable", True):
                tests.append("not_null")
            if col.get("unique", False):
                tests.append("unique")
            if tests:
                yaml_lines.append("        tests:")
                for test in tests:
                    yaml_lines.append(f"          - {test}")

        return "\n".join(yaml_lines)

    def generate_snapshot(self, snapshot_name: str, target_schema: str, unique_key: str, updated_at: str) -> str:
        """Generate a dbt snapshot file for SCD Type 2 tracking."""
        snapshot_sql = f"""{{% snapshot {snapshot_name} %}}

{{{{
    config(
      target_database=target_database,
      target_schema='{target_schema}',
      unique_key='{unique_key}',
      strategy='timestamp',
      updated_at='{updated_at}',
    )
}}}}

select * from {{{{ source('raw', '{snapshot_name}_src') }}}}

{{% endsnapshot %}}
"""
        return snapshot_sql

    def generate_macro(self, macro_name: str, column_name: str) -> str:
        """Generate a dbt Jinja macro."""
        macro_code = f"""{{% macro {macro_name}({column_name}) %}}
    case
        when {column_name} is null then 'Unknown'
        else {column_name}
    end
{{% endmacro %}}
"""
        return macro_code


def get_dbt_agent() -> DbtAgent:
    """Get dbt agent instance."""
    return DbtAgent()
